### PR TITLE
teal.reporter - bs345

### PR DESCRIPTION
**Pull request by Polkas**
linked to https://github.com/insightsengineering/teal/issues/719

- [x] previewer accordion working under bootstrap 3,4 and 5
- [x] fix the previewer vignette app layout, previously broken under bootstrap 4 and 5

### CODE REVIEW

**Comment by asbates** [comment]
Not sure if it should go here or in `teal` but here goes. I'm having issues with theming and `teal.reporter`. More specifically, setting the `teal.bs_theme` doesn't seem to make any changes.

The app I'm running is from `teal.reporter` [Simple Reporter vignette](https://insightsengineering.github.io/teal.reporter/main/articles/simpleReporter.html). From within `teal` branch `709_bs345@main`

```
devtools::load_all(".")
library(shiny)
library(teal.reporter)
library(ggplot2)
library(rtables)

options("teal.bs_theme" = bslib::bs_theme(version = 5, primary = 'purple'))

ui <- fluidPage(
  titlePanel(""),
  sidebarLayout(
    sidebarPanel(
      uiOutput("encoding")
    ),
    mainPanel(
      ### REPORTER
      shiny::tags$div(
        teal.reporter::add_card_button_ui("addReportCard"),
        teal.reporter::download_report_button_ui("downloadButton"),
        teal.reporter::reset_report_button_ui("resetButton")
      ),
      ###
      shiny::tags$br(),
      tabsetPanel(
        id = "tabs",
        tabPanel("Plot", plotOutput("dist_plot")),
        tabPanel("Table", verbatimTextOutput("table"))
      )
    )
  )
)

server <- function(input, output, session) {
  output$encoding <- renderUI({
    if (input$tabs == "Plot") {
      sliderInput(
        "binwidth",
        "binwidth",
        min = 2,
        max = 10,
        value = 8
      )
    } else {
      selectInput(
        "stat",
        label = "Statistic",
        choices = c("mean", "median", "sd"),
        "mean"
      )
    }
  })
  
  plot <- reactive({
    req(input$binwidth)
    x <- mtcars$mpg
    ggplot2::ggplot(data = mtcars, ggplot2::aes(x = mpg)) +
      ggplot2::geom_histogram(binwidth = input$binwidth)
  })
  
  output$dist_plot <- renderPlot({
    plot()
  })
  
  table <- reactive({
    req(input$stat)
    lyt <- basic_table() %>%
      split_rows_by("Month", label_pos = "visible") %>%
      analyze("Ozone", afun = eval(str2expression(input$stat)))
    
    build_table(lyt, airquality)
  })
  
  output$table <- renderPrint({
    table()
  })
  
  ### REPORTER
  reporter <- teal.reporter::Reporter$new()
  card_fun <- function(card = ReportCard$new(), comment) {
    if (input$tabs == "Plot") {
      card$append_text("My plot", "header2")
      card$append_plot(plot())
    } else if (input$tabs == "Table") {
      card$append_text("My Table", "header2")
      card$append_table(table())
    }
    if (!comment == "") {
      card$append_text("Comment", "header3")
      card$append_text(comment)
    }
    card
  }
  
  teal.reporter::add_card_button_srv("addReportCard", reporter = reporter, card_fun = card_fun)
  teal.reporter::download_report_button_srv("downloadButton", reporter = reporter)
  teal.reporter::reset_report_button_srv("resetButton", reporter)
  ###
}

if (interactive()) shinyApp(ui = ui, server = server)
```

The app runs fine but the bootstrap version is still 3.x 
image

``` r
sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rtables_0.5.2.1           formatters_0.3.3.1        ggplot2_3.3.6             teal.reporter_0.1.0.9029  teal_0.11.1.9023         
 [6] testthat_3.1.4            teal.transform_0.1.1.9015 magrittr_2.0.3            teal.data_0.1.1.9013      shiny_1.7.2              

loaded via a namespace (and not attached):
 [1] fs_1.5.2                teal.logger_0.1.0.9014  usethis_2.1.6           fontawesome_0.3.0       devtools_2.4.4          rprojroot_2.0.3        
 [7] R.cache_0.16.0          tools_4.2.1             profvis_0.3.7           backports_1.4.1         bslib_0.4.0             utf8_1.2.2             
[13] R6_2.5.1                DBI_1.1.3               colorspace_2.0-3        urlchecker_1.0.1        withr_2.5.0             tidyselect_1.1.2       
[19] prettyunits_1.1.1       processx_3.6.1          compiler_4.2.1          textshaping_0.3.6       cli_3.4.0               shinyjs_2.1.0          
[25] desc_1.4.1              labeling_0.4.2          sass_0.4.2              scales_1.2.1            checkmate_2.1.0         callr_3.7.0            
[31] systemfonts_1.0.4       stringr_1.4.0           digest_0.6.29           rmarkdown_2.14          teal.slice_0.1.1.9016   R.utils_2.12.0         
[37] pkgconfig_2.0.3         htmltools_0.5.3         teal.widgets_0.1.1.9013 sessioninfo_1.2.2       styler_1.7.0            fastmap_1.1.0          
[43] htmlwidgets_1.5.4       rlang_1.0.5             rstudioapi_0.13         farver_2.1.1            jquerylib_0.1.4         generics_0.1.3         
[49] jsonlite_1.8.0          dplyr_1.0.10            R.oo_1.25.0             Rcpp_1.0.9              munsell_0.5.0           fansi_1.0.3            
[55] logger_0.2.2            lifecycle_1.0.2         R.methodsS3_1.8.2       stringi_1.7.6           yaml_2.3.5              brio_1.1.3             
[61] pkgbuild_1.3.1          grid_4.2.1              teal.code_0.1.1.9008    promises_1.2.0.1        crayon_1.5.1            miniUI_0.1.1.1         
[67] knitr_1.39              ps_1.7.1                pillar_1.8.1            pkgload_1.3.0           glue_1.6.2              evaluate_0.15          
[73] remotes_2.4.2           vctrs_0.4.1             httpuv_1.6.6            gtable_0.3.1            purrr_0.3.4             assertthat_0.2.1       
[79] cachem_1.0.6            xfun_0.31               mime_0.12               xtable_1.8-4            later_1.3.0             ragg_1.2.2             
[85] tibble_3.1.8            memoise_2.0.1           shinyWidgets_0.7.3      ellipsis_0.3.2

```

**Comment by Polkas** [comment]
Please start with reading of [the new bslib related vignette](https://github.com/insightsengineering/teal/blob/709_bs345%40main/vignettes/teal-bs-themes.Rmd).

So the teal.bs_theme option is injected to any teal::init app. 
The teal.reporter package is independent of any other NEST solution, so you will not find a teal::init like example app here. 
If you want to update the theme for this app it will be as simple as providing the theme directly to fluidPage:

```
fluidPage(theme = bslib::bs_theme(...), ...)
```

**Comment by asbates** [comment]
> Please start with reading of [the new bslib related vignette](https://github.com/insightsengineering/teal/blob/709_bs345%40main/vignettes/teal-bs-themes.Rmd).
> 
> So the teal.bs_theme option is injected to any teal::init app. The teal.reporter package is independent of any other `teal` solution, so you will not find a teal::init like example app here. If you want to update the theme for this app it will be as simple as providing the theme directly to fluidPage:
> 
> ```
> fluidPage(theme = bslib::bs_theme(...), ...)
> ```

Sorry! So obvious now, I guess I jumped the gun.

**Review by mhallal1 — APPROVED** [review]
LGTM.
a NEWS entry maybe?

**Comment by asbates** [comment]
I'm getting different layouts with different bootstrap versions using the example app in the [Reporter Previewer vignette](https://insightsengineering.github.io/teal.reporter/main/articles/previewerReporter.html). Adding a `theme = bslib::bs_theme(version = <3,4,5>)` to the `fluidPage` gives below for version 3, 4, 5.


image (1)


image (3)


image (4)

**Comment by mhallal1** [comment]
> I'm getting different layouts with different bootstrap versions using the example app in the [Reporter Previewer vignette](https://insightsengineering.github.io/teal.reporter/main/articles/previewerReporter.html). Adding a `theme = bslib::bs_theme(version = <3,4,5>)` to the `fluidPage` gives below for version 3, 4, 5.
> 
> image (1)
> 
> image (3)
> 
> image (4)

I confirm this issue with theme `4`, please create an issue describing the above.

**Comment by asbates** [comment]
> > I'm getting different layouts with different bootstrap versions using the example app in the [Reporter Previewer vignette](https://insightsengineering.github.io/teal.reporter/main/articles/previewerReporter.html). Adding a `theme = bslib::bs_theme(version = <3,4,5>)` to the `fluidPage` gives below for version 3, 4, 5.
> ...
> 
> I confirm this issue with theme `4`, please create an issue describing the above.

@mhallal1 turns out this was already caught and fixed with commit 70068a301093683dfadc994a0c9cfe2efd8f78ec. The issue was with the example app code and ordering of `sidebarLayout`/`uiOutput`. The updated vignette has the [fixed, working example application](https://github.com/insightsengineering/teal.reporter/blob/2a2b2bf09d02421bad911e36c423c38acface46b/vignettes/previewerReporter.Rmd#L39).

**Pull request merged**
