### PR TITLE
Enable listings support & table annotations in `to_flextable`

### LINKED ISSUE #217: Enable listings support & table annotations in `to_flextable`
The most recent version of `teal.reporter` implements the `to_flextable()` function to print tables. This function drops all annotations (i.e. titles/footnotes) that have been added to the table in the case of `rtables` objects. In my opinion the best solution would be to update the `to_flextable()` function in `teal.reporter` as follows:

1) Update the function to print table titles/footnotes for supported formats.
2) Add `listings_df` as a supported format in the function since listings also have a matrix print form and can be handled the same as `rtables` objects (no extra work should be needed).

_Originally posted by @edelarua in https://github.com/insightsengineering/teal.modules.clinical/issues/834#issuecomment-1734440055_

### PR DESCRIPTION
**Pull request by edelarua**
Closes #217

### CODE REVIEW

**Comment by edelarua** [comment]
Example report output:

ex_report

**Comment by kartikeyakirar** [comment]
Should we add `listing_df` to the list of supported formats in [TableBlock.R](https://github.com/insightsengineering/teal.reporter/blob/4fa942ec6c8c72f466505b969244c7a70d7e9f28/R/TableBlock.R#L35)?

**Comment by edelarua** [comment]
> `listing_df` should be added as list of supported formats in [TableBlock.R](https://github.com/insightsengineering/teal.reporter/blob/4fa942ec6c8c72f466505b969244c7a70d7e9f28/R/TableBlock.R#L35)?

@kartikeyakirar yes - thanks for spotting that! I have added `"listing_df"` to `TableBlock` as well.

**Review by kartikeyakirar — APPROVED** [review]
this looks good 👍

**Pull request merged**
