### PR TITLE
208 CRAN requirements for the first submission [skip vbump]

### LINKED ISSUE #201: Release `teal.reporter` to CRAN
### Summary
The objective is to make `teal.reporter` available on CRAN. 
I ran R CMD check locally and everything looks good so we probably don't need to do a preliminary release before pushing to CRAN.

### Acceptance Criteria
* Add/Confirm the `--as-cran` option in CICD pipeline
* R CMD Check passed or create new issue to fix
  * If there is an issue, then we'll need a preliminary release
  * Might as well perform the README task and the vignettes grouping
  * Perform release activities (full version bump and git tag)
* Push to CRAN

### LINKED ISSUE #208: Fix CRAN issues
Please do not start the description with "This package", package name,
title or similar.

The Description field is intended to be a (one paragraph) description of
what the package does and why it may be useful. Please add more details
about the package functionality and implemented methods in your
Description text.

Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: --> 'shiny'
Please note that package names are case sensitive.

The LICENSE file is only needed if you have additional restrictions to
the license which you have not? In that case omit the file and its
reference in the DESCRIPTION file.

"Using foo:::f instead of foo::f allows access to unexported objects.
This is generally not recommended, as the semantics of unexported
objects may be changed by the package author in routine maintenance."
Used ::: in documentation:
      man/Archiver.Rd:
         archiver <- teal.reporter:::Archiver$new()
      man/ContentBlock.Rd:
         block <- teal.reporter:::ContentBlock$new()
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("TRUE")
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("True")
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("off")
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("n")
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("sth")
      man/FileArchiver.Rd:
         archiver <- teal.reporter:::FileArchiver$new()
      man/FileBlock.Rd:
         block <- teal.reporter:::FileBlock$new()
      man/JSONArchiver.Rd:
         card1 <- teal.reporter:::ReportCard$new()
      man/JSONArchiver.Rd:
         reporter <- teal.reporter:::Reporter$new()
      man/JSONArchiver.Rd:
         archiver <- teal.reporter:::JSONArchiver$new()
      man/JSONArchiver.Rd:
         blocks <- teal.reporter:::Reporter$new()$
[... truncated]
Please omit one colon.

Please fix and resubmit.

### PR DESCRIPTION
**Pull request by m7pr**
Closes #208 Closes #201
- satisfies DESCRIPTION requirements. 
- needed to remove `:::` from documentation - this required to 
    - update `teal.reporter:::ReportCard` to `teal.reporter::ReportCard` as this is exported object
    - update `teal.reporter:::Report` to `teal.reporter::Report` as this is exported object
    - delete `$append_content()` method examples as they used `teal.reporter:::NewpageBlock` which is unexported
    - delete manual pages for internal, unexported objects: `Archiver`, `ContentBlock`, `FileArchiver`, `FileBlock`, `JSONArchiver`, `NewpageBlock`, `PictureBlock`, `RcodeBlock`, `Renderer`
        - above can still be visible in `R/` directory in the source code of classes

### CODE REVIEW

**Comment by m7pr** [comment]
Tagging @chlebowa @gogonzo and @donyunardi to let you know that internal manual pages will not be accepted on CRAN as they use `:::` sign to access non-exported functions.

**Comment by donyunardi** [comment]
We will use this PR to track CRAN feedback/update/release and GH release based on our release process steps.

So I will:
1. Up-version the package (0.2.1) + update PR title to skip vbump.
2. Built this locally and submit to CRAN
3. git tag v0.2.1-rc# and push
4. Address any CRAN feedback and repeat steps 2 and 3 until CRAN approves.
5. Once in CRAN, then we will merge this to main and tag v0.2.1 for GH release

We probably need to block any PR to main during this time.

**Comment by donyunardi** [comment]
> delete manual pages for internal, unexported objects: Archiver, ContentBlock, FileArchiver, FileBlock, JSONArchiver, NewpageBlock, PictureBlock, RcodeBlock, Renderer
above can still be visible in R/ directory in the source code of classes

Since we are removing the .Rd files for internal and unexported objects, should we be more consistent by adding the `@noRd` tag to all internal and unexported objects and functions?

For example:
https://github.com/insightsengineering/teal.reporter/blob/55e890abb7ba165f6bf6754e86fa21f2d11dc2b5/R/DownloadModule.R#L155-L156

If so, perhaps we should make it consistent throughout all teal packages?

**Comment by gogonzo** [comment]
Please remove examples where `:::` occurs. I get a response as follows:

> Since these examples are for unexported functions and are accessed in their examples, please do not use examples for unexported functions at all. Those functions are only ment to be used internally. If you believe they need examples, then they probably should be exported.

--------------

In this PR I see some examples were changed from `:::` to `::` does it work?

**Comment by m7pr** [comment]
Hey @gogonzo the change from `:::` to `::` worked only for exported functions `teal.reporter:::ReportCard` -> `teal.reporter::ReportCard` and `teal.reporter:::Report` -> `teal.reporter::Report`.

For non-exported functions I will only delete examples and will bring back manual pages (without examples) so `noRd` tag disappears. We can move examples for non-exported functions to `dev/examples.R` file, that will be added to `.Rbuildignore` so it's not added to the sourced package that we will re-submit to CRAN

**Comment by m7pr** [comment]
Hey, just moved examples do `dev/internal_examples.R`

**Comment by m7pr** [comment]
@donyunardi would you like to take care of a resubmission to CRAN?

**Comment by donyunardi** [comment]
Resubmitted to CRAN as 0.2.1.
Creating tag 0.2.1-rc1.
Waiting for further CRAN feedback.

**Comment by m7pr** [comment]
Resubmitted again to CRAN as 0.2.1. after we received https://github.com/insightsengineering/teal.reporter/issues/208#issuecomment-1711154795

**Review by gogonzo — APPROVED** [review]

**Comment by donyunardi** [comment]
Create and push v0.2.1-rc2 tag.
Hopefully this is it 🤞🏼

**Comment by donyunardi** [comment]
teal.reporter is now in CRAN:
https://cran.r-project.org/web/packages/teal.reporter/index.html

**Pull request merged**
